### ISSUE TITLE
Error in function getOClient()

### ISSUE THREAD

**Issue by MrMagloire** [cmohammadc/laravel-api-auth#1]
Hello, thank you so much for all.
But i your code i don't see where you save data in oauth_clients table, because the function can't get data with getOClient().
I want to understand because in my database I have nothing in the oauth_clients table after see your tutorial on : https://dev.to/azibom/how-do-you-make-laravel-7-api-authentication-with-passport-like-a-master-2p67

**Comment by MrMagloire** [comment]
I remember I did a reset of my base before

**Comment by azibom** [comment]
Hi Magloire,
For generating clients in oauth_clients table you need to run this command
"php artisan passport:client"

Good luck

**Comment by MrMagloire** [comment]
@cmohammadc  Thank you,
Everything is ok now but my request does not stop, it spends its time until I stop it myself.
When I do on purpose not to fill all fields then I have a return to tell me that the field is required but when everything is ok there is no return until I stop the request.

**Comment by MrMagloire** [comment]
![Uploading 84898510...]()

**Comment by MrMagloire** [comment]
![WhatsApp Image 2020-06-17 at 13 39 39](https://user-images.githubusercontent.com/9309214/84899039-0eeeac00-b0a0-11ea-87f1-25627ad2d256.jpeg)
![WhatsApp Image 2020-06-17 at 13 39 40](https://user-images.githubusercontent.com/9309214/84899043-0f874280-b0a0-11ea-924c-e8882580baa3.jpeg)

**Comment by azibom** [comment]
Did you change your BASE_URL in UserRepository class?

**Comment by MrMagloire** [comment]
Yes I change It to my my Api Url : `http://localhost:8000` generate by `php artisan serve`

**Comment by azibom** [comment]
The problem is related to "php artisan serve" it uses php server which is single thread so you need to use a web server like Nginx or if you want to get quick fix you can do this
run these both in two different command prompts
```
php artisan serve
```
And
```
php artisan serve --port 8001  
```
And then change your BASE_URL to "http://127.0.0.1:8001" 
Now you have two threads and it works like a charm :))

**Comment by MrMagloire** [comment]
Thank you very much, it works now
